show tables;

select * from ird_trade i ;

select i.index_name from ird_leg i ;

-- IRD Dtcc Trade Report
select
	'' AS "Comment 1",
	'' AS "Action",
	'Core1.0' AS "Version",
	'Trade State' AS "Message Type",
	'LEI' AS "Submitting Party - ID Type",
	'549300F8NR5Q23JRIY74' AS "Submitting Party - ID",
	'25490072C0PMGDUJQU77' AS "Submitted For Party",
	'InterestRate' AS "Primary Asset Class",
	'LEI' AS "Trade Party 1 - ID Type",
	'25490072C0PMGDUJQU77' AS "Trade Party 1 - ID",
	'LEI' AS "Trade Party 2 - ID Type",
	'2549009X2AG1P20YAJ63' AS "Trade Party 2 - ID",
	'CFTC' AS "Trade Party 1 - Reporting Destination",
	'CFTC' AS "Trade Party 2 - Reporting Destination",
	'' AS "Product ID Type",
	'InterestRate:IRSwap:FixedFloat' AS "Product ID",
	'' AS "Trade Party 1 - Execution Agent ID Type",
	'' AS "Trade Party 1 - Execution Agent ID",
	'' AS "Trade Party 2 - Execution Agent ID Type",
	'' AS "Trade Party 2 - Execution Agent ID",
	'' AS "Trade Party 1 - Third Party Viewer ID Type",
	'' AS "Trade Party 1 - Third Party Viewer ID",
	' ' AS "Trade Party 2 - Third Party Viewer ID Type",
	' ' AS "Trade Party 2 - Third Party Viewer ID",
	' ' AS "Trade Party 1 - Country of the Other Counterparty",
	' ' AS "Trade Party 2 - Country of the Other Counterparty",
	' ' AS "Trade Party 1 - Branch Location",
	' ' AS "Trade Party 2 - Branch Location",
	' ' AS "Trade Party 1 - Corporate Sector Type",
	' ' AS "Trade Party 2 - Corporate Sector Type",
	' ' AS "Trade Party 1 - Nature of the Reporting Counterparty",
	' ' AS "Trade Party 2 - Nature of the Reporting Counterparty",
	' ' AS "Trade Party 1 - Broker ID Type",
	' ' AS "Trade Party 1 - Broker ID",
	' ' AS "Trade Party 2 - Broker ID Type",
	' ' AS "Trade Party 2 - Broker ID",
	' ' AS "Trade Party 1 - Clearing Broker ID Type",
	' ' AS "Trade Party 1 - Clearing Broker ID",
	' ' AS "Trade Party 2 - Clearing Broker ID Type",
	' ' AS "Trade Party 2 - Clearing Broker ID",
	' ' AS "Trade Party 1 - Beneficiary ID Type",
	' ' AS "Trade Party 1 - Beneficiary ID",
	' ' AS "Trade Party 2 - Beneficiary ID Type",
	' ' AS "Trade Party 2 - Beneficiary ID",
	' ' AS "Trade Party 1 - Trading Capacity 1",
	' ' AS "Trade Party 1 - Trading Capacity 2",
	' ' AS "Trade Party 2 - Trading Capacity 1",
	' ' AS "Trade Party 2 - Trading Capacity 2",
	' ' AS "Trade Party 1 - Counterparty Side",
	' ' AS "Trade Party 2 - Counterparty Side",
	' ' AS "Trade Party 1 - Directly linked to commercial activity or treasury financing Indicator",
	' ' AS "Trade Party 2 - Directly linked to commercial activity or treasury financing Indicator",
	' ' AS "Trade Party 1 - Clearing Threshold",
	' ' AS "Trade Party 2 - Clearing Threshold",
	' ' AS "Trade Party 1 - Collateral Portfolio Code",
	' ' AS "Trade Party 2 - Collateral Portfolio Code",
	' ' AS "Trade Party 1 - Regulatory Action Type 1",
	' ' AS "Trade Party 2 - Regulatory Action Type 1",
	' ' AS "Trade Party 1 - Event ID",
	' ' AS "Trade Party 2 - Event ID",
	' ' AS "Trade Party 1 - Transaction ID",
	' ' AS "Trade Party 2 - Transaction ID",
	' ' AS "Trade Date",
	' ' AS "Contract Type",
	' ' AS "Product Classification Type",
	' ' AS "Product Classification",
	' ' AS "Product identification type",
	' ' AS "Product identification",
	' ' AS "EU Underlying Asset ID Type",
	' ' AS "EU Underlying Asset ID",
	td.trade_uuid AS "UTI ID",
	'UTI-001' AS "UTI ID Prefix",
	' ' AS "Report Tracking Number",
	' ' AS "Complex Trade Component ID",
	' ' AS "Execution Venue - ID Type",
	' ' AS "Execution Venue - ID",
	' ' AS "Compressed Trade Indicator",
	td.notional AS "Notional Amount 1",
	td.notional AS "Notional Amount 2",
	payLeg.currency AS "Notional Currency 1",
	recLeg.currency AS "Notional Currency 2",
	' ' AS "Price Multiplier",
	DATE_FORMAT(td.execution_time , '%Y-%m-%dT%H:%i:%sZ') AS "Original Execution Timestamp",  -- Currently we don't have Original Execution Timestamp
	' ' AS "Master Agreement Type",
	' ' AS "Master Agreement Version",
	' ' AS "Mandatory Clearing Jurisdiction",
	'N' AS "Clearing Status", -- lots of things 
	' ' AS "Clearing DateTime",
	' ' AS "Intragroup Indicator",
	' ' AS "Payment 1 - Type",
	' ' AS "Payment 1 - Amount",
	' ' AS "Payment 1 - Currency",
	' ' AS "Payment 1 - Date",
	' ' AS "Payment 2 - Type",
	' ' AS "Payment 2 - Amount",
	' ' AS "Payment 2 - Currency",
	' ' AS "Payment 2 - Date",
	' ' AS "Payment 1 - Frequency Period",
	' ' AS "Payment 2 - Frequency Period",
	' ' AS "Payment 1 - Frequency Period Multiplier",
	' ' AS "Payment 2 - Frequency Period Multiplier",
	date_format(td.maturity_date, '%Y-%m-%d' ) AS "Maturity Date of the Underlying",
	' ' AS "Level",
	' ' AS "As of Date Time",
	' ' AS "Lifecycle Event Type",
	' ' AS "Message ID",
	date_format(td.effective_date, '%Y-%m-%d' ) AS "Effective Date 1",
	' ' AS "Post Trade Effective Date",
	' ' AS "Clearing Venue - ID Type",
	' ' AS "Clearing Venue - ID",
	' ' AS "Number of Options",
	' ' AS "Price 1 - Price",
	' ' AS "Price 1 - Type",
	' ' AS "Price 1 - Units",
	' ' AS "Strike Price",
	' ' AS "Strike Price - Units",
	' ' AS "Scheduled Termination Date 1",
	' ' AS "Settlement Type",
	td.revalCcy  AS "Settlement Currency 1",
	' ' AS "Settlement Date",
	' ' AS "Option Type",
	' ' AS "Option Style",
	' ' AS "Confirmation Date Time",
	' ' AS "Confirmation Method",
	' ' AS "Quantity",
	' ' AS "Seniority",
	' ' AS "Reference Entity",
	' ' AS "Series",
	' ' AS "CR-Version",
	' ' AS "Index Factor",
	' ' AS "Tranche",
	' ' AS "Attachment Point",
	' ' AS "Exhaustion Point",
	date_format(td.last_payment_date, '%Y-%m-%d' ) AS "Leg 2 - Settlement Date",
	' ' AS "Exchange Rate",
	' ' AS "Rate Quote Basis 1",
	' ' AS "Rate Quote Basis 2",
	' ' AS "Exchange Rate Basis Currency 1",
	' ' AS "Exchange Rate Basis Currency 2",
	' ' AS "Day Count Fraction 1",
	' ' AS "Expiration Date",
	' ' AS "Leg 2 - Designated Maturity Period",
	' ' AS "Leg 2 - Designated Maturity Period Multiplier",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	payLeg.fixed_rate AS "Leg 1 - Fixed Rate Initial",
	payLeg.index_name AS "Leg 1 - Floating Rate Index",
	REGEXP_REPLACE(payLeg.index_tenor, '[0-9]', '') AS "Leg 1 - Floating Rate Tenor Period",
	REGEXP_REPLACE(payLeg.index_tenor, '[^0-9]', '') AS "Leg 1 - Floating Rate Tenor Period Multiplier",
	recLeg.day_count AS "Leg 2 - Day Count Fraction",
	date_format(td.effective_date, '%Y-%m-%d' ) AS "Leg 2 - Effective Date",
	recLeg.fixed_rate AS "Leg 2 - Fixed Rate Initial",
	recLeg.index_name AS "Leg 2 - Floating Rate Index",
	REGEXP_REPLACE(recLeg.index_tenor, '[0-9]', '') AS "Leg 2 - Floating Rate Tenor Period",
	REGEXP_REPLACE(recLeg.index_tenor, '[^0-9]', '') AS "Leg 2 - Floating Rate Tenor Period Multiplier",
	' ' AS "Leg 2 - Scheduled Termination Date",
	' ' AS "Leg 2 - Settlement Currency",
	-- ' ' AS "Reset Frequency Period 1",
	CASE
		WHEN payLeg.reset_frequency = 'Quarterly' THEN 'QTR'
		WHEN payLeg.reset_frequency = 'Monthly' THEN 'MNTH'
		WHEN payLeg.reset_frequency = 'Yearly' THEN 'YR'
		WHEN payLeg.reset_frequency = 'Weekly' THEN 'WK'
		WHEN payLeg.reset_frequency = 'Daily' THEN 'DAY'
		ELSE payLeg.reset_frequency
	END AS "Reset Frequency Period 1",
	CASE
		WHEN recLeg.reset_frequency = 'Quarterly' THEN 'QTR'
		WHEN recLeg.reset_frequency = 'Monthly' THEN 'MNTH'
		WHEN recLeg.reset_frequency = 'Yearly' THEN 'YR'
		WHEN recLeg.reset_frequency = 'Weekly' THEN 'WK'
		WHEN recLeg.reset_frequency = 'Daily' THEN 'DAY'
		ELSE recLeg.reset_frequency
	END AS "Leg 2 - Reset Frequency Period",
-- 	' ' AS "Leg 2 - Reset Frequency Period",
	' ' AS "Reset Frequency Period Multiplier 1",
	REGEXP_REPLACE(recLeg.index_tenor, '[^0-9]', '') AS "Leg 2 - Reset Frequency Period Multiplier",
	' ' AS "Number of Shares / Units",
	' ' AS "Post Trade Transaction Date",
	' ' AS "Variance Amount",
	' ' AS "Commodity Base",
	' ' AS "Commodity details",
	' ' AS "Days of the Week",
	' ' AS "Delivery Capacity",
	' ' AS "Delivery End Date and Time",
	' ' AS "Delivery Point",
	' ' AS "Delivery Start Date and Time",
	' ' AS "Duration",
	' ' AS "Exercise Expiration Date Unadjusted",
	' ' AS "Exercise Payment Date Unadjusted",
	' ' AS "Expiration Date Unadjusted",
	' ' AS "Interconnection Point",
	' ' AS "Leg 1 - Effective Date Unadjusted",
	' ' AS "Leg 1 - Payment Dates Unadjusted",
	' ' AS "Leg 2 - Effective Date Unadjusted",
	' ' AS "Leg 2 - Payment Date Unadjusted",
	' ' AS "Load Delivery Intervals",
	' ' AS "Load Type",
	' ' AS "Premium Payment Date Unadjusted",
	' ' AS "Price Time Interval Quantities",
	' ' AS "Quantity Unit",
	' ' AS "Settlement Date Unadjusted",
	' ' AS "Termination Date Unadjusted",
	' ' AS "Trade Party 1 - Collateralization Type",
	' ' AS "Trade Party 2 - Collateralization Type",
	' ' AS "Trade Party 1 - Collateral Portfolio",
	' ' AS "Trade Party 2 - Collateral Portfolio",
	' ' AS "Execution Venue - MIC Code",
	' ' AS "Reserved - Participant Use 1",
	' ' AS "Reserved - Participant Use 2",
	' ' AS "Reserved - Participant Use 3",
	' ' AS "Reserved - Participant Use 4",
	' ' AS "Reserved - Participant Use 5",
	' ' AS "Trade Party 1 - Mandatory Delegated Reporting",
	' ' AS "Trade Party 2 - Mandatory Delegated Reporting",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Barrier Type 2",
	' ' AS "Trigger Condition",
	' ' AS "Trigger Condition 2",
	' ' AS "Currency of Price",
	' ' AS "Trade Leg Types",
	' ' AS "Premium Amount",
	' ' AS "Premium Currency",
	' ' AS "Forward Exchange Rate",
	' ' AS "Leg 1 – Fixed Rate Notation",
	' ' AS "Leg 2 - Fixed Rate Notation",
	' ' AS "AI Party 1 - ID Type",
	' ' AS "AI Party 1 - ID",
	' ' AS "AI Party 2 - ID Type",
	' ' AS "AI Party 2 - ID",
	' ' AS "Trade Party 1 - Domicile",
	' ' AS "Trade Party 2 - Domicile",
	' ' AS "Trade Party 1 - Name",
	' ' AS "Trade Party 2 - Name",
	' ' AS "Trade Party 1 - Trader Location",
	' ' AS "Trade Party 2 - Trader Location",
	' ' AS "Transaction Type",
	' ' AS "USI ID Prefix",
	' ' AS "USI ID",
	' ' AS "Prior USI ID Prefix",
	' ' AS "Prior USI ID",
	' ' AS "Prior UTI ID Prefix",
	' ' AS "Prior UTI ID",
	' ' AS "Execution Venue Type",
	' ' AS "Expiration Time",
	' ' AS "Expiration Date/Time Business Center",
	DATE_FORMAT(td.execution_time , '%Y-%m-%dT%H:%i:%sZ') AS "Latest Execution DateTime",
	'25490072C0PMGDUJQU77' AS "Buyer / Payer 1",
	'2549009X2AG1P20YAJ63' AS "Seller / Payer 2",
	' ' AS "Underlying Asset ID Type",
	' ' AS "Underlying Asset ID",
	' ' AS "Underlying Asset Name",
	' ' AS "Option Entitlement",
	' ' AS "Payment 1 - Payer",
	' ' AS "Payment 1 - Reference",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Leg 2 - Payment Dates",
	' ' AS "Payment 2 - Payer",
	' ' AS "Payment 2 - Reference",
	' ' AS "Payment 3 - Type",
	' ' AS "Payment 3 - Amount",
	' ' AS "Payment 3 - Currency",
	' ' AS "Payment 3 - Date",
	' ' AS "Payment 3 - Payer",
	' ' AS "Payment 3 - Reference",
	' ' AS "Payment 3 - Frequency Period",
	' ' AS "Payment 3 - Frequency Period Multiplier",
	' ' AS "Payment 3 - Reset Frequency Period",
	' ' AS "Payment 3 - Reset Frequency Period Multiplier",
	' ' AS "Payment 4 - Type",
	' ' AS "Payment 4 - Amount",
	' ' AS "Payment 4 - Currency",
	' ' AS "Payment 4 - Date",
	' ' AS "Payment 4 - Payer",
	' ' AS "Payment 4 - Reference",
	' ' AS "Payment 4 - Frequency Period",
	' ' AS "Payment 4 - Frequency Period Multiplier",
	' ' AS "Payment 4 - Reset Frequency Period",
	' ' AS "Payment 4 - Reset Frequency Period Multiplier",
	' ' AS "Payment 5 - Type",
	' ' AS "Payment 5 - Amount",
	' ' AS "Payment 5 - Currency",
	' ' AS "Payment 5 - Date",
	' ' AS "Payment 5 - Payer",
	' ' AS "Payment 5 - Reference",
	' ' AS "Payment 5 - Frequency Period",
	' ' AS "Payment 5 - Frequency Period Multiplier",
	' ' AS "Payment 5 - Reset Frequency Period",
	' ' AS "Payment 5 - Reset Frequency Period Multiplier",
	' ' AS "Premium Payer",
	' ' AS "Strike Price - Currency",
	' ' AS "Reference Entity ID",
	' ' AS "Underlying Fixed Rate Payer (Buyer)",
	' ' AS "Underlying Float Rate Payer (Seller)",
	' ' AS "Swap link ID",
	' ' AS "Trigger Rate",
	' ' AS "Trigger Rate 2",
	' ' AS "Barrier Type",
	' ' AS "Earliest Execution Time",
	' ' AS "Execution Period Start Date",
	' ' AS "Cap Rate - initial",
	' ' AS "Floor Rate - Initial",
	' ' AS "Leg 1 - Floating Rate Initial Spread",
	' ' AS "Leg 1 - Notional Step Date",
	' ' AS "Leg 1 - Notional Step Values",
	' ' AS "Leg 2 - Floating Rate Initial Spread",
	' ' AS "Leg 2 - Notional Step Date",
	' ' AS "Leg 2 - Notional Step Values",
	' ' AS "Premium Receiver",
	' ' AS "Swaption Straddle Indicator",
	' ' AS "Underlying Product ID",
	' ' AS "Dividend Payment Date",
	' ' AS "Leg 1 - Payment Dates",
	' ' AS "Floating Rate Option",
	' ' AS "Underlying Asset Equity Amount Payer",
	' ' AS "Underlying Asset Equity Amount Receiver",
	' ' AS "Underlying Asset Exchange ID",
	' ' AS "Fixed Amount Payment Date",
	' ' AS "Knock In Event",
	' ' AS "Knock In Price",
	' ' AS "Knock Out Event",
	' ' AS "Knock Out Price",
	' ' AS "Leg 1 - Commodity Instrument ID",
	' ' AS "Leg 1 - Commodity Underlyer Details",
	' ' AS "Leg 1 - Notional Quantity Frequency",
	' ' AS "Leg 1 - Notional Quantity Schedule Settlement Step",
	' ' AS "Leg 1 - Party Payer",
	' ' AS "Leg 1 - Party Receiver",
	' ' AS "Leg 1 - Quantity Frequency",
	' ' AS "Leg 1 - Total Notional Quantity",
	' ' AS "Leg 2 - Commodity Instrument ID",
	' ' AS "Leg 2 - Commodity Underlyer Details",
	' ' AS "Leg 2 - Notional Quantity Frequency",
	' ' AS "Leg 2 - Notional Quantity Schedule Settlement Step",
	' ' AS "Leg 2 - Party Payer",
	' ' AS "Leg 2 - Total Notional Quantity",
	' ' AS "Commencement Date Unadjusted",
	' ' AS "Delivery Location",
	' ' AS "Product Grade",
	' ' AS "Quantity Schedule",
	' ' AS "Total Quantity",
	' ' AS "GTR Quantity Unit",
	' ' AS "Exercise Dates",
	DATE_FORMAT(NOW(), '%Y-%m-%dT%H:%i:%sZ') AS "Reporting Timestamp",
	' ' AS "Value Date",
	' ' AS "Confirmation Platform ID",
	' ' AS "Confirmation Platform Trade ID",
	' ' AS "Execution Type",
	'false' AS "Non Standard Trade Indicator",
	' ' AS "Secondary Asset Class",
	' ' AS "Trade Party 1 - Desk Location",
	' ' AS "Trade Party 2 - Desk Location",
	' ' AS "Trade Party 1 - HK Counterparty Origin",
	' ' AS "Trade Party 2 - HK Counterparty Origin",
	' ' AS "Trade Party 1 - Industrial Sector Type",
	' ' AS "Trade Party 2 - Industrial Sector Type",
	' ' AS "Cancelation Option - Buyer",
	' ' AS "Cancelation Option - Commencement Date",
	' ' AS "Cancelation Option - Exercise Dates",
	' ' AS "Cancelation Option - Exercise Style Type",
	' ' AS "Cancelation Option - Expiration Date",
	' ' AS "Cancelation Option - Initial Fee Currency",
	' ' AS "Cancelation Option - Initial Fee Payer",
	' ' AS "Cancelation Option - Premium Amount",
	' ' AS "Cancelation Option - Relevant Underlying Dates",
	' ' AS "Cancelation Option - Seller",
	' ' AS "Cap Rate - Step Date",
	' ' AS "Cap Rate - Step Values",
	' ' AS "Coupon Type",
	' ' AS "Floor Rate - Step Date",
	' ' AS "Floor Rate - Step Value",
	' ' AS "FRA - Discounting Type",
	' ' AS "Inflation Index - Initial Level",
	' ' AS "Inflation Index - Main Publication",
	' ' AS "Inflation Interpolation Method",
	' ' AS "Inflation Lag - Day Type",
	' ' AS "Inflation Lag - Period",
	' ' AS "Inflation Lag - Period Multiplier",
	' ' AS "Inflation Rate - Source Name",
	' ' AS "Initial Principal Exchange Indicator",
	' ' AS "Intermediate Principal Exchange Indicator",
	' ' AS "Final Principal Exchange Indicator (at Termination)",
	' ' AS "Leg 1 - Fixed Rate Step Date",
	' ' AS "Leg 1 - Fixed Rate Step Values",
	' ' AS "Leg 1 - Floating Rate Multiplier Initial Value",
	' ' AS "Leg 1 - Floating Rate Multiplier Step Date",
	' ' AS "Leg 1 - Floating Rate Multiplier Step Values",
	' ' AS "Leg 1 - Floating Rate Spread Step Date",
	' ' AS "Leg 1 - Floating Rate Spread Step Values",
	' ' AS "Leg 1 - Known Amount",
	' ' AS "Leg 1 - Known Amount Currency",
	' ' AS "Leg 1 - Reference Currency",
	' ' AS "Leg 2 - Fixed Rate Step Date",
	' ' AS "Leg 2 - Fixed Rate Step Values",
	' ' AS "Leg 2 - Floating Rate Multiplier Initial Value",
	' ' AS "Leg 2 - Floating Rate Multiplier Step Date",
	' ' AS "Leg 2 - Floating Rate Multiplier Step Values",
	' ' AS "Leg 2 - Floating Rate Spread Step Date",
	' ' AS "Leg 2 - Floating Rate Spread Step Values",
	' ' AS "Leg 2 - Known Amount",
	' ' AS "Leg 2 - Known Amount Currency",
	' ' AS "Leg 2 - Reference Currency",
	' ' AS "Mandatory Early Termination Date",
	' ' AS "Mandatory Early Termination Date Tenor Period",
	' ' AS "Mandatory Early Termination Date Tenor Period Multiplier",
	' ' AS "Notional Units",
	' ' AS "Optional Early Termination - Commencement Date",
	' ' AS "Optional Early Termination - Dates",
	' ' AS "Optional Early Termination - Exercise Adjusted Dates",
	' ' AS "Optional Early Termination - Exercise Dates",
	' ' AS "Optional Early Termination - Exercise Style",
	' ' AS "Optional Early Termination - Expiration Date",
	' ' AS "Optional Early Termination - Underlying Dates",
	' ' AS "Relevant Underlying Dates - Unadjusted Dates",
	' ' AS "Single Party Early Termination - Buyer",
	' ' AS "Underlying Coupon Rate",
	' ' AS "Underlying Maturity Date",
	' ' AS "Settlement Fixing Date",
	' ' AS "Payout Style",
	' ' AS "Dividend Amount Payer",
	' ' AS "Dividend Amount Receiver",
	' ' AS "Fixed Amount Payer",
	' ' AS "Fixed Amount Receiver",
	' ' AS "Leg 1 - Type of Return",
	' ' AS "Leg 1 - Valuation Dates",
	' ' AS "Material Non-Cash Dividend Indicator",
	' ' AS "Observation Start Date",
	' ' AS "Optional Early Termination Electing Party Value",
	' ' AS "Optional Early Termination Indicator",
	' ' AS "Optional Early Termination Type",
	' ' AS "Period End Date",
	' ' AS "Period Fixed Amount",
	' ' AS "Period Fixed Strike",
	' ' AS "Period Start Date",
	' ' AS "Reference Currency",
	' ' AS "Special Dividends Indicator",
	' ' AS "Underlying Asset Fixed Rate",
	' ' AS "Underlying Asset Floating Amount Payer",
	' ' AS "Underlying Asset Floating Amount Receiver",
	' ' AS "Underlying Asset Floating Leg Spread",
	' ' AS "Underlying Asset Initial Price",
	' ' AS "Underlying Asset Initial Price Currency",
	' ' AS "Underlying Asset Notional Amount",
	' ' AS "Underlying Asset Notional Currency",
	' ' AS "Underlying Asset Number of Units",
	' ' AS "Variance Cap Factor",
	' ' AS "Variance Strike Price",
	' ' AS "Volatility Strike Price",
	' ' AS "Basket Weight Percentage",
	' ' AS "Mth To Default",
	' ' AS "Nth To Default",
	' ' AS "Payment 1 - Receiver",
	' ' AS "Reference Entity - ID Type",
	' ' AS "Reference Obligation - ID Type",
	' ' AS "Reference Obligation",
	' ' AS "Reference Obligation - Type",
	' ' AS "Underlying Asset - Place of Incorporation",
	' ' AS "Underlying Asset - Place of Issuance",
	' ' AS "CO Product Type",
	' ' AS "Coal Source",
	' ' AS "Electricity Physical Leg Delivery Step Quantity",
	' ' AS "Electricity Physical Leg Delivery Step Quantity Frequency",
	' ' AS "Electricity Physical Leg Delivery Step Quantity Unit",
	' ' AS "Fixed Price",
	' ' AS "Fixed Price Currency",
	' ' AS "Fixed Price Schedule Step(s)",
	' ' AS "Fixed Price Unit",
	' ' AS "Leg 1 - Commodity Currency",
	' ' AS "Leg 1 - Commodity Exchange ID",
	' ' AS "Leg 1 - Commodity Rate Source",
	' ' AS "Leg 1 - Commodity Rate Source Page",
	' ' AS "Leg 1 - Commodity Underlyer ID",
	' ' AS "Leg 1 - Commodity Unit of Measure",
	' ' AS "Leg 1 - Notional Quantity",
	' ' AS "Leg 1 - Notional Quantity Schedule Step",
	' ' AS "Leg 1 - Notional Quantity Unit",
	' ' AS "Leg 1 - Quantity",
	' ' AS "Leg 1 - Quantity Unit",
	' ' AS "Leg 1 - Specified Price",
	' ' AS "Leg 1 - Spread Amount",
	' ' AS "Leg 1 - Spread Currency",
	' ' AS "Leg 1 - Spread Schedule",
	' ' AS "Leg 2 - Commodity Currency",
	' ' AS "Leg 2 - Commodity Exchange ID",
	' ' AS "Leg 2 - Commodity Rate Source",
	' ' AS "Leg 2 - Commodity Rate Source Page",
	' ' AS "Leg 2 - Commodity Underlyer ID",
	' ' AS "Leg 2 - Commodity Unit of Measure",
	' ' AS "Leg 2 - Notional Quantity",
	' ' AS "Leg 2 - Notional Quantity Schedule Step",
	' ' AS "Leg 2 - Notional Quantity Unit",
	' ' AS "Leg 2 - Party Receiver",
	' ' AS "Leg 2 - Quantity",
	' ' AS "Leg 2 - Quantity Unit",
	' ' AS "Leg 2 - Specified Price",
	' ' AS "Leg 2 - Spread Amount",
	' ' AS "Leg 2 - Spread Currency",
	' ' AS "Leg 2 - Spread Schedule",
	' ' AS "Strike Price Schedule",
	' ' AS "Total Quantity Unit",
	' ' AS "Commencement Date",
	' ' AS "Embedded Option on Swap",
	' ' AS "Leg 1 - Effective Date",
	' ' AS "Leg 1 - Termination Date",
	' ' AS "HKMA Special Terms",
	' ' AS "HKMA Remarks 1",
	' ' AS "HKMA Remarks 2",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Reserved Field - For Future Use",
	' ' AS "Origin",
	' ' AS "Clearing Member Client Account ID",
	' ' AS "Clearing Swap USI ID Prefix",
	' ' AS "Clearing Swap USI ID",
	' ' AS "Clearing Swap UTI Prefix",
	' ' AS "Clearing Swap UTI ID",
	' ' AS "Original Swap SDR  - ID Type",
	' ' AS "Original Swap SDR - ID",
	' ' AS "Clearing Receipt DateTime",
	' ' AS "Clearing Exception Type",
	'False' AS "Trade Party 1 - CFTC Financial Entity Status",
	'FALSE' AS "Trade Party 2 - CFTC Financial Entity Status",
	' ' AS "Recovery Price",
	' ' AS "Price 2 - Price",
	' ' AS "Price 2 - Units",
	'UNAL' AS "Allocation Type",
	' ' AS "Large Trade Indicator",
	' ' AS "Clearing Swap SDR LEI - ID",
	' ' AS "Trade Party 1 - Role",
	' ' AS "Trade Party 2 - Role",
	' ' AS "Trade Party 1 - Local Counterparty Jurisdiction",
	' ' AS "Trade Party 2 - Local Counterparty Jurisdiction",
	' ' AS "Clearing Exception Party - ID Type",
	' ' AS "Clearing Exception Party - ID",
	' ' AS "Prior USI Type",
	' ' AS "Prior UTI Type",
	' ' AS "Inter-Affiliate",
	' ' AS "Leg 1 - Settlement Period",
	' ' AS "Responsible Data Submitter – ID Type",
	' ' AS "Responsible Data Submitter – ID",
	' ' AS "Original Swap USI",
	' ' AS "Original Swap UTI",
	' ' AS "Clearing Exception Type - Party 2",
	' ' AS "CDE - Receiver identifier-Leg 2",
	'TRUE' AS "Counterparty 1 federal entity indicator",
	'TRUE' AS "Counterparty 2 federal entity indicator",
	'FALSE' AS "Custom basket indicator",
	'NEWT' AS "NoA - Action Type",
	'TRAD' AS "Event Type",
	'FALSE' AS "Amendment indicator",
	' ' AS "Event identifier",
	' ' AS "CDE - Call amount-Leg 1",
	' ' AS "CDE - Call amount-Leg 2",
	' ' AS "CDE - Call currency-Leg 1",
	' ' AS "CDE - Call currency-Leg 2",
	' ' AS "CDE - Put amount-Leg 1",
	' ' AS "CDE - Put amount-Leg 2",
	' ' AS "CDE - Put currency-Leg 1",
	' ' AS "CDE - Put currency-Leg 2",
	' ' AS "Leg 2 - Quantity Frequency",
	' ' AS "Quantity frequency multiplier-Leg 1",
	' ' AS "Quantity frequency multiplier-Leg 2",
	' ' AS "CDE - Quantity unit of measure-Leg 1",
	' ' AS "CDE - Quantity unit of measure-Leg 2",
	'FALSE' AS "Package indicator",
	' ' AS "CDE - Package identifier",
	' ' AS "CDE - Package transaction price",
	' ' AS "CDE - Package transaction price currency",
	' ' AS "CDE - Package transaction price notation",
	' ' AS "CDE - Package transaction spread",
	' ' AS "CDE - Package transaction spread currency",
	' ' AS "CDE - Package transaction spread notation",
	' ' AS "CDE - Fixed rate day count convention-leg 1",
	' ' AS "CDE - Fixed rate day count convention-leg 2",
	' ' AS "CDE - Floating rate day count convention-leg 1",
	' ' AS "CDE - Floating rate day count convention-leg 2",
	' ' AS "Fixing date-Leg 1",
	' ' AS "Fixing date-Leg 2",
	' ' AS "CDE - Other payment payer",
	' ' AS "CDE - Other payment receiver",
	' ' AS "CDE - Fixed rate payment frequency period-Leg 1",
	' ' AS "CDE - Fixed rate payment frequency period-Leg 2",
	' ' AS "CDE - Floating rate payment frequency period-Leg 1",
	' ' AS "CDE - Floating rate payment frequency period-Leg 2",
	' ' AS "CDE - Fixed rate payment frequency period multiplier-Leg 1",
	' ' AS "CDE - Fixed rate payment frequency period multiplier-Leg 2",
	' ' AS "CDE - Floating rate payment frequency period multiplier-Leg 1",
	' ' AS "CDE - Floating rate payment frequency period multiplier-Leg 2",
	'FALSE' AS "Post-priced swap indicator",
	' ' AS "CDE - Price currency",
	' ' AS "CDE - Price notation",
	'' AS "CDE - Spread notation-Leg 1",
	'4' AS "CDE - Spread notation-Leg 2", -- TODO
	' ' AS "CDE - Strike Price - Currency 2",
	' ' AS "CDE - Strike price notation",
	' ' AS "CDE - First Exercise Date",
	date_format(td.maturity_date, '%Y-%m-%d' ) AS "CDE - Final contractual settlement date",
	' ' AS "CDE - Settlement location-Leg 1",
	' ' AS "CDE - Settlement location-Leg 2",
	date_format(td.effective_date, '%Y-%m-%d' ) AS "CDE - Effective Date",
	date_format(td.maturity_date, '%Y-%m-%d' ) AS "CDE - Expiration Date",
	'XXXX' AS "CDE - Platform identifier",
	'N' AS "Prime brokerage transaction indicator",
	'CFTC' AS "Swap Reporting Jurisdiction",
	' ' AS "New SDR identifier",
	'false' AS "Large notional off-facility swap election indicator",
	td.notional AS "CDE - Notional amount in effect on associated effective date-Leg 1",
	td.notional AS "CDE - Notional amount in effect on associated effective date-Leg 2",
	date_format(td.effective_date, '%Y-%m-%d' ) AS "CDE - Effective date of the notional amount-Leg 1",
	date_format(td.effective_date, '%Y-%m-%d' ) AS "CDE - Effective date of the notional amount-Leg 2",
	' ' AS "CDE - End date of the notional amount-Leg 1",
	' ' AS "CDE - End date of the notional amount-Leg 2",
	' ' AS "SEF or DCM Anonymous Execution Indicator",
	' ' AS "Initial margin collateral portfolio code",
	' ' AS "Variation margin collateral portfolio code",
	' ' AS "CDE - Other payment type",
	' ' AS "CDE - Other payment amount",
	' ' AS "CDE - Other payment currency",
	' ' AS "CDE - Other payment date",
	'FALSE' AS "Block trade election indicator",
	'FALSE' AS "SEF or DCM Indicator",
	'FALSE' AS "Mandatory clearing indicator",
	'FALSE' AS "SD MSP indicator - Counterparty 1",
	'FALSE' AS "SD MSP indicator - Counterparty 2",
	' ' AS "Physical commodity contract indicator",
	' ' AS "Corporate Action - New Trade Party 1 LEI",
	' ' AS "Change in Notional Amount 1",
	' ' AS "Change in Notional Amount 2",
	' ' AS "Change in Leg 1 - Notional quantity",
	' ' AS "Change in Leg 2 - Notional quantity",
	'QZKXMFQ1FWM3' AS "UPI (Unique Product Identifier)",
	' ' AS "Other payment payer ID Type",
	' ' AS "Other payment receiver ID Type"
from
	ird_product prd
inner join ird_trade td on
	(td.trade_uuid = prd.trade_uuid )
left join ird_leg payLeg on
	(payLeg.product_uuid = prd.product_uuid
		and payLeg.leg_type = 'pay')
	-- Leg1
left join ird_leg recLeg on
	(recLeg.product_uuid = prd.product_uuid
		and recLeg.leg_type = 'receive')
	-- Leg2
where
	prd.asset_type = 'Vanilla'
	and td.trade_no in (1204, 1205);






select
	*
from
	ird_trade i
order by
	i.trade_no desc;

-- Leg 1 as PayLeg and it can be fixed or float )
select * from ird_leg i

select
payLeg.leg_type  payLegType,
payLeg.fixed_float payLegFixedFloat,
recLeg.leg_type  recLegType,
recLeg.fixed_float recLegFixedFloat,
payLeg.index_tenor ,
	i.*
from
	ird_product i
inner join ird_trade i2 on
	(i.trade_uuid = i2.trade_uuid )
left join ird_leg payLeg on
	(payLeg.product_uuid = i.product_uuid
		and payLeg.leg_type = 'pay')
left join ird_leg recLeg on
	(recLeg.product_uuid = i.product_uuid
		and recLeg.leg_type = 'receive')
where
	i.asset_type = 'Vanilla'
	and i2.trade_no in (1203,1202);
